# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      IS_PIPELINE: 'true'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Fetch Raylib 
      run: |
        mkdir raylib
        cd raylib
        git clone https://github.com/raysan5/raylib.git .
        git checkout e65d15f6ad6f9ade05999b66fdd91d3f6eb2a2d0
        
    - name: Generate and Build Raylib Solution 
      run: |
        .\setupshell.ps1
        &dir
        cd raylib
        cmake -G  "Visual Studio 16 2019" -A x64 -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -S . -B bin
        &devenv .\bin\Project.sln /Build "RelWithDebInfo|x64"
        Move-Item -Path .\bin\src\RelWithDebInfo\ -Destination ..\Binaries_x64
        cmake -G  "Visual Studio 16 2019" -A Win32 -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -S . -B bin
        &devenv .\bin\Project.sln /Build "RelWithDebInfo|Win32"
        Move-Item -Path .\bin\src\RelWithDebInfo\ -Destination ..\Binaries_x86
        
